### ISSUE TITLE
zetteldeft creates a file with 2 same titles

### ISSUE THREAD

**Issue by OrionRandD** [EFLS/zetteldeft#70] opened 2020-06-27 15:16 UTC
I am using zetteldeft in Emacs doom.

My configuration is as follow for deft and zetteldeft:

(use-package! deft
   :custom
    (deft-directory "~/org~/deft-notes")
    (deft-extensions '("org" "md"))
    (deft-recursive t)
    (deft-use-filename-as-title nil)
    (deft-filter-only-filenames t)
    (deft-auto-save-interval 30.0)
    (deft-file-limit 200))

(defun cypher/deft-open-other ()
(interactive)
(deft-open-file-other-window t))

(defun cypher/deft-open-preview ()
  (interactive)
  (deft-open-file-other-window))

(with-eval-after-load 'deft
  (define-key deft-mode-map
    (kbd "<tab>") 'cypher/deft-open-preview)
  (define-key deft-mode-map
    (kbd "<s-return>") 'cypher/deft-open-other)
  (define-key deft-mode-map
    (kbd "s-j") 'evil-next-line)
  (define-key deft-mode-map (kbd "s-k") 'evil-previous-line))

(setq deft-strip-summary-regexp
      (concat "\\("
              "[\n\t]"                   ;; blank
              "\\|^#\\+[a-zA-Z_]+:.*$"   ;;org-mode metadata
              "\\)"))

(use-package! zetteldeft
  :after deft
  :config
  (setq deft-new-file-format zetteldeft-id-format)
  (zetteldeft-set-classic-keybindings))

(defun zetteldeft-generate-id ()
  "Generate an ID in the format of `zetteldeft-id-format'."
  (format-time-string zetteldeft-id-format))

The proble is when I create a new file with zetteldeft, the file come with two 
same titles which is very annoying...

e.g.

#+TITLE: 2020 06 27 1213 New Annoying Zet File

#+TITLE: new_annoying_zetFile

I do not know what I am missing or doing wrong with the
above configuration
Help please

**Comment by vlnn** [comment] 2020-06-27 18:25
I can confirm that behaviour in doom emacs and every workarounds I've found had some side effects (like not generating proper title at all)

**Comment by EFLS** [comment] 2020-06-28 08:55
Annoying indeed. Seems related to #26.

When you say “create a new file with zettelfdeft”, you mean using `C-c d n`? Or via the Deft search bar? And is there a difference between the two methods?

**Comment by vlnn** [comment] 2020-06-28 15:36
M-x zetteldeft-new-file (Enter)

**Comment by vlnn** [comment] 2020-06-28 15:51
Adding magical
```
(after! zetteldeft
(setq zetteldeft-title-prefix nil))
```
to the `config.el` seems to be working for me (after the latest updates), providing file with two lines (second empty):
`2020-06-28-1849 fixed new zettel name`

Not sure this is intended behaviour though, as I would expect to have only text in the title...

**Comment by OrionRandD** [comment] 2020-06-29 18:29
@vlnn  thx a lot. The "Adding magical" fixed the "issue/bug".
:)

**Comment by lluca2** [comment] 2020-07-01 06:47
this is what worked for me but not sure if it doesn't break some org-mode template behavior though:
(source: https://dotdoom.rgoswami.me/config.html)

add this line to your ~/.doom.d/config.el :
(set-file-template! "\\.org$" :ignore t) 

hope it helps!

**Comment by EFLS** [comment] 2020-07-01 17:10
Note that setting `zetteldeft-title-prefix` to nil can interfere with other functions, such as the rename function, as it is used to locate and update the title.

I'm closing this issue. Discussion and tracing can continue in #26.

**Closed by EFLS** 2020-07-01 17:10 UTC
